######################################################################
# Automatically generated by qmake (3.0) Fri Jan 23 17:23:32 2015
######################################################################
CONFIG += qt
QT += widgets
TEMPLATE = app
TARGET = tictactoe
INCLUDEPATH += .

# Input
HEADERS += commoninclude.hpp mainboard.hpp tictactoe.hpp analyze_game.hpp
SOURCES += main.cpp mainboard.cpp tictactoe.cpp analyze_game.cpp
